### ISSUE TITLE
netbase package required

### ISSUE THREAD

**Issue by ncafferkey** [ErezHorev/dockerized_nfs_server#1]
When I rebuilt the image, nfs-kernel-server failed to start with this error:

unable to resolve ANYADDR:nfs to inet address: Name or service not known

I discovered that the container had no /etc/services file, which was resolved by installing the netbase package.

**Comment by ErezHorev** [comment]
@ncafferkey, thank you for raising that issue ;)
I'm looking into to it ...

**Comment by ErezHorev** [comment]
@ncafferkey, i can't seem to reproduce your issue (on linux mint), what OS (+version) is the machine you built on ? (feel free to provide any other info that might be relevant. e.g. kernel ..etc)

In any case, adding netbase might be suitable here as suggested, do you want to contribute (you'll be the first!) , if so then add it to the Dockerfile and send a pull request, if not that's ok as well ;)

**Comment by ncafferkey** [comment]
My host is Ubuntu 14.04.4 LTS. I'm happy for you to make any change required, as I'm a git newbie.

**Comment by ErezHorev** [comment]
awsome then we'll do it. 
few more questions please:
how did you build the image? did you run 'docker build..' or used the 'start.sh' scripts?
whats docker version are you using?

**Comment by ncafferkey** [comment]
I encountered the error when I built it with "sudo docker build -t erezhorev/dockerized_nfs_server" when I wanted to start making changes. I had previously been using the downloaded image successfully with start.sh. Docker version 1.11.0 build 4dc5990.

**Comment by ErezHorev** [comment]
thanks. i must be 100% sure that the fix is required so have few more questions please.

If the start.sh worked correctly i'm suspecting one of your changes might caused it to fail.
can you please try build from the original code without your changes ? basically just:
1. git clone this repo to some tmp dir
2. from inside that dir run: `docker build -t mynfs .`
3. then run it to see it works: `docker run --privileged --rm --name mynfs mynfs`

if it works then please elaborate what your added changes are.

Thank you

**Comment by ncafferkey** [comment]
No, a clean build (done as described above) still doesn't work. Note that start.sh only worked for me with the pre-built image that I downloaded (at least I think that's how Docker works, doesn't it?). I notice that the pre-built image is apparently based on Ubuntu 14.04.3 (I had that cached on a second machine), whereas my local builds are based on 16.04. I'm going to try a new build based explicitly on 14.04.3 to see if that helps.

**Comment by ncafferkey** [comment]
Using "FROM ubuntu:14.04.3" did indeed work around the problem.

**Comment by ErezHorev** [comment]
sorry for the late response @ncafferkey 
good analysis! your assumptions about docker are correct.
At the current point, i think its better to be based on a specific Ubuntu version in order to preserve stability and clarity of which version we're using. besides that, i'm not fully aware of all changes on latest ubuntu versions so other issues might pop up as well.
Therefor think the fix should be to change the ubuntu version on the Dockerfile to a fixed version as you described (14.04) .
what do you think ?

> FROM Ubuntu

to 

> FROM ubuntu:14.04

It is also mentioned in the [user guide](https://docs.docker.com/engine/userguide/containers/dockerimages/):

> Tip: You should always specify an image tag, for example ubuntu:14.04. That way, you always know exactly what variant of an image you are using. This is useful for troubleshooting and debugging.

**Comment by ErezHorev** [comment]
ping @ncafferkey

**Comment by ErezHorev** [comment]
Thank you @ncafferkey for raising this.
Currently set to ubuntu:14.04

**Comment by ncafferkey** [comment]
Yes, it's probably the more pragmatic solution to pin it to a specific Ubuntu version, but it would be nice in future to have support for newer Ubuntu versions. Also, sorry for disappearing off the radar: I got really busy for a while.

**Comment by ErezHorev** [comment]
I agree.
No harm done ;)
