### ISSUE TITLE
Stop - SIGTERM is not caught inside the container...

### ISSUE THREAD

**Issue by manojchaudhari76** [ErezHorev/dockerized_nfs_server#8]
Hi,

I am trying to see if stop (SIGTERM) is captured using run.sh file and nfs-kernel-server is stopped. 
But it seems it is not doing this. 

I am issuing  : docker kill -s"SIGTERM" container...
Nothing in the logs ...it stays as is...
- Initializing nfs server..
 * Exporting directories for NFS kernel daemon...
   ...done.
 * Starting NFS kernel daemon
   ...done.
- Nfs server is up and running..

The issue I am trying to tackle here is, if I don't stop NFS server, while removing container running on storage devicemapper (loop) and i am not allowed to remove container/s using this NFS server. 

Eventually with docker rm -v container the status of container is "Dead".

Any help is appreciated!

thanks,

**Comment by manojchaudhari76** [comment]
This looks to me more of devicemapper (loop) issue than nfs container. I have tried to setup devicemapper with thin pool and now it looks to be catching the SIGTERM signal...
I am closing this issue but someone should be fixing devicemapper (loop) related issue.

**Comment by ErezHorev** [comment]
@manojchaudhari76 thanks for raising this issue ;)
I can't see how catching the SIGTERM is related to the devicemapper but i'm going to test it anyway just to make sure.
The docker storage (devicemapper with loopback device in this case) is a configuration matter, this project is pretty agnostic to docker's storage and shouldn't be effected by it.
Personally, i can recommend not to use loopback device since its really slow and bloating overtime but for testing and experiencing with the project its good enough.

**Comment by ErezHorev** [comment]
@manojchaudhari76 i've tested it under centos using a devicemapper with thin pool (not a loopback) and it works like you described.
If you run ./stop.sh you'll miss the 'stopping' message.
Please try again on loopback again but this time instead of using stop.sh script just run:
`docker stop mynfs ; docker logs mynfs`

You should get the container's output which shows the SIGTERM is being handled ("Stopping NFS kernel daemon":

```
Export points:
/exports/ *(rw,sync,insecure,fsid=0,no_subtree_check,no_root_squash)

- Initializing nfs server..
 * Not starting NFS kernel daemon: no support in current kernel.
- Nfs server is up and running..
- Shutting down nfs-server..
 * Stopping NFS kernel daemon
   ...done.
 * Unexporting directories for NFS kernel daemon...
   ...done.
- Nfs server is down
```
