### ISSUE TITLE
Failed to acquire lock on .lock file...

### ISSUE THREAD

**Issue by manojchaudhari76** [ErezHorev/dockerized_nfs_server#9]
Hello,

I am back with some other issue this time...

I am deploying a container with Kafka in it and I am putting kafka log as a volume mounted from this image.
I mount volume with this command : mount -t nfs -o rw,proto=tcp,port=2049 IP:/path /path

But when I try to start the kafka for the first time, it is not able to acquire log on the .lock file. This file is created on kafka log path which is a mounted path. The .lock file is created though...

One more thing, if I remove the .lock file manually and then try to start kafka, it would start without any problem.

I was wondering if you could have any pointers for me! appreciate your help! thanks,

here is error : 

[2017-11-28 06:12:56,193] FATAL [Kafka Server 2], Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
kafka.common.KafkaException: Failed to acquire lock on file .lock in /usr/local/kafka-logs. A Kafka instance in another process or thread is using this directory.
	at kafka.log.LogManager.$anonfun$lockLogDirs$1(LogManager.scala:107)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:34)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at kafka.log.LogManager.lockLogDirs(LogManager.scala:103)
	at kafka.log.LogManager.<init>(LogManager.scala:65)
	at kafka.server.KafkaServer.createLogManager(KafkaServer.scala:658)
	at kafka.server.KafkaServer.startup(KafkaServer.scala:208)
	at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:39)
	at kafka.Kafka$.main(Kafka.scala:67)
	at kafka.Kafka.main(Kafka.scala)

**Comment by ErezHorev** [comment]
Hi @manojchaudhari76
Sorry for the late response and hope i can help ;)

I'm suspecting a non gracefull shutdown of your kafka container leaving behind this lock file in the persistent volume.

Here's what i think is happening.
1. raising kafka (#1) for the first time - no lock file yet
2. kafka #1 is up - lock file created on volume
3. kafka #1 is down - lock file still exists on volume
4. raising kafka #2 new instance (lock file exists on volume), kafka abort since lock file is found.

resolution:
two options i have in mind
1. if possible, redirect lock file destination to reside outside the volume which will end up to be cleaned automatically when its container is dead.
2. find out online how to gracefully shutdown Kafka in a sence that the lock file will be deleted  by its service before closing/killing the container.
3. last and probably the easiest, delete the .lock file from the volume before running the Kafka service/container like you did yourself. you can wrap your Kafka invokation with a shell script that removes it from the volume. another option if building the Kafka image yourself, update its Dockerfile entrypoint to call such script/functionality of file removal before running the server.

Hope something in the above helped
share your results ;)

**Comment by ErezHorev** [comment]
Hi @manojchaudhari76
Sorry for the late response and hope i can help ;)

I'm suspecting a non gracefull shutdown of your kafka container leaving behind this lock file in the persistent volume.

Here's what i think is happening.
1. raising kafka (#1) for the first time - no lock file yet
2. kafka #1 is up - lock file created on volume
3. kafka #1 is down - lock file still exists on volume
4. raising kafka #2 new instance (lock file exists on volume), kafka abort since lock file is found.

resolution:
three options i have in mind
1. if possible, redirect lock file destination to reside outside the volume which will end up to be cleaned automatically when its container is dead.
2. find out online how to gracefully shutdown Kafka in a sense that the lock file is deleted by its service before closing/killing the container.
3. last and probably the easiest, delete the .lock file from the volume before running the Kafka service/container like you did yourself. you can wrap your Kafka invocation with a shell script that removes it from the volume. another option if building the Kafka image yourself, update its Dockerfile entrypoint to call such script/functionality of file removal before running the server.

Hope something in the above helped
share your results ;)

**Comment by manojchaudhari76** [comment]
Hello @ErezHorev , hope you are doing well...!

I had tried those things already...the previous shutdown of kafka seems ok, at least no .lock is left back on the disk. It is trying to recreate it and fails to acquire lock for this attempt only. (it is new .lock file, no earlier file is found in "ls -la" )

I am running few more tests I will keep you posted for additional information.

Thanks, 
-Manoj :)

**Comment by ErezHorev** [comment]
Hi @manojchaudhari76 ,
I'm great thanks, likewise 
weird...
good luck :)
